name: recog
version: "1.5.1"
license: "GPL-3.0-or-later"
date: 2026-05-19
description: |
    A package for constructive recognition of permutation and matrix groups

authors:
    - name: Max Neunhöffer
      url: mailto:max@9hoeffer.de
    - name: Ákos Seress

maintainers:
    - name: Max Horn
      url: https://www.quendi.de/math

contributors:
    - name: Nurullah Ankaralioglu
      url: mailto:ankarali@atauni.edu.tr
    - name: Dominik Bernhardt
      url: mailto:bernhardt@mathb.rwth-aachen.de
    - name: Peter Brooksbank
      url: mailto:pbrooksb@bucknell.edu
    - name: Frank Celler
      url: mailto:frank@celler.de
    - name: Paula Hähndel
      url: mailto:paula.haehndel@mathematik.uni-halle.de
    - name: Stephen Howe
    - name: Alexander Hulpke
      url: https://www.math.colostate.edu/~hulpke/
    - name: Christopher Jefferson
      url: mailto:caj21@st-andrews.ac.uk
    - name: Maska Law
      url: mailto:maska@maths.uwa.edu.au
    - name: Steve Linton
      url: mailto:sal@cs.st-andrews.ac.uk
    - name: Gunter Malle
      url: https://agag-malle.math.rptu.de/~malle/en/
    - name: Till Müller
      url: mailto:t.mueller@math.rptu.de
    - name: Alice Niemeyer
      url: http://www.math.rwth-aachen.de/~Alice.Niemeyer/
    - name: Eamonn O'Brien
      url: https://www.math.auckland.ac.nz/~obrien/
    - name: Colva M. Roney-Dougal
      url: mailto:colva@mcs.st-and.ac.uk
    - name: Sergio Siccha
      url: mailto:sergio@mathb.rwth-aachen.de
    - name: Martin Wagner
      url: mailto:marwagne@rptu.de
    - name: Torben Wiedemann
      url: mailto:torben.wiedemann@rptu.de
    - name: Wilf Wilson
      url: https://wilf.me
    - name: Madeleine Whybrow
      url: https://madeleinewhybrow.wordpress.com/contact/

GAP: ">=4.13"

needed-pkgs:
    - name: "AtlasRep"
      version: ">= 2.1.0"
      url: "https://www.math.rwth-aachen.de/~Thomas.Breuer/atlasrep"
    - name: "FactInt"
      version: ">= 1.6.3"
      url: "https://gap-packages.github.io/FactInt"
    - name: "Forms"
      version: ">= 1.2.11"
      url: "https://gap-packages.github.io/forms"
    - name: "genss"
      version: ">= 1.6.8"
      url: "https://gap-packages.github.io/genss"
    - name: "Orb"
      version: ">= 4.9.0"
      url: "https://gap-packages.github.io/orb"

www: https://gap-packages.github.io/recog
readme: README.md
packageinfo: https://gap-packages.github.io/recog/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/recog/releases/download/v1.5.1/recog-1.5.1.tar.gz
    - name: .tar.bz2
      url: https://github.com/gap-packages/recog/releases/download/v1.5.1/recog-1.5.1.tar.bz2

abstract: |
    
        <p><b>Warning:</b> This package is still under development and
        this version is to be considered a working, but preliminary one.</p>
    
        <p>This package contains a collection of methods for the
        constructive recognition of groups. It is mostly intended for
        permutation groups, matrix groups and projective groups.</p>
        

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    group recognition, matrix group recognition, permutation group, black box group, composition tree, Aschbacher classes, method selection.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>NS26</span>]   <b class='BibAuthor'>Neunhöffer, M. and Seress, Á.</b>,
     <i class='BibTitle'>recog, A package for constructive recognition of permutation and matrix groups,
             Version 1.5.1</i>
     (<span class='BibYear'>2026</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/recog">https://gap-packages.github.io/recog</a></span>.
    </p>
    

bibtex: |
    @misc{ recog,
      author =           {Neunh{\"o}ffer, M. and Seress, {\a'A}.},
      title =            {{recog},  {A  package  for constructive recognition of
                          permutation and matrix groups}, {V}ersion 1.5.1},
      month =            {May},
      year =             {2026},
      note =             {GAP package},
      howpublished =     {\href           {https://gap-packages.github.io/recog}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{recog}}},
      keywords =         {group    recognition;    matrix   group   recognition;
                          permutation  group; black box group; composition tree;
                          Aschbacher classes; method selection},
      printedkey =       {NS26}
    }

