name: recog
version: 1.4.0
date: 2022-09-22
description: |
    A package for constructive recognition of permutation and matrix groups

authors:
    - name: Max Neunhöffer
      url: mailto:max@9hoeffer.de
    - name: Ákos Seress

maintainers:
    - name: Max Horn
      url: https://www.quendi.de/math

contributors:
    - name: Dominik Bernhardt
      url: mailto:bernhardt@mathb.rwth-aachen.de
    - name: Nurullah Ankaralioglu
      url: mailto:ankarali@atauni.edu.tr
    - name: Peter Brooksbank
      url: mailto:pbrooksb@bucknell.edu
    - name: Frank Celler
      url: mailto:frank@celler.de
    - name: Paula Hähndel
      url: https://algebra.mathematik.uni-halle.de/haehndel/
    - name: Alexander Hulpke
      url: https://www.math.colostate.edu/~hulpke/
    - name: Stephen Howe
    - name: Christopher Jefferson
      url: https://caj.host.cs.st-andrews.ac.uk
    - name: Maska Law
      url: mailto:maska@maths.uwa.edu.au
    - name: Steve Linton
      url: http://www-groups.mcs.st-and.ac.uk/~sal
    - name: Gunter Malle
      url: https://www.mathematik.uni-kl.de/~malle/
    - name: Alice Niemeyer
      url: http://www.math.rwth-aachen.de/~Alice.Niemeyer/
    - name: Eamonn O'Brien
      url: https://www.math.auckland.ac.nz/~obrien/
    - name: Colva M. Roney-Dougal
      url: http://www-groups.mcs.st-and.ac.uk/~colva
    - name: Sergio Siccha
      url: mailto:sergio@mathb.rwth-aachen.de
    - name: Wilf Wilson
      url: https://wilf.me
    - name: Madeleine Whybrow
      url: https://madeleinewhybrow.wordpress.com/contact/

GAP: ">=4.11"

needed-pkgs:
    - name: "AtlasRep"
      version: ">= 1.4.0"
      url: "https://www.math.rwth-aachen.de/~Thomas.Breuer/atlasrep"
    - name: "FactInt"
      version: ">= 1.5.2"
      url: "https://gap-packages.github.io/FactInt"
    - name: "Forms"
      version: ">= 1.2"
      url: "https://gap-packages.github.io/forms"
    - name: "genss"
      version: ">= 1.3"
      url: "https://gap-packages.github.io/genss"
    - name: "Orb"
      version: ">= 3.4"
      url: "https://gap-packages.github.io/orb"

www: https://gap-packages.github.io/recog
readme: README.md
packageinfo: https://gap-packages.github.io/recog/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/recog/releases/download/v1.4.0/recog-1.4.0.tar.gz
    - name: .tar.bz2
      url: https://github.com/gap-packages/recog/releases/download/v1.4.0/recog-1.4.0.tar.bz2

abstract: |
    
        <p><b>Warning:</b> This package is still under development and
        this version is to be considered a working, but preliminary one.</p>
    
        <p>This package contains a collection of methods for the
        constructive recognition of groups. It is mostly intended for
        permutation groups, matrix groups and projective groups.</p>
        

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    group recognition, matrix group recognition, permutation group, black box group, composition tree, Aschbacher classes, method selection.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>NSH22</span>]   <b class='BibAuthor'>Neunhöffer, M., Seress, Á. and Horn, M.</b>,
     <i class='BibTitle'>recog, A package for constructive recognition of permutation and matrix groups,
             Version 1.4.0</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/recog">https://gap-packages.github.io/recog</a></span>.
    </p>
    

bibtex: |
    @misc{ recog1.4.0,
      author =           {Neunh{\"o}ffer, M. and Seress, {\a'A}. and Horn, M.},
      title =            {{recog},  A  package  for  constructive recognition of
                          permutation and matrix groups, {V}ersion 1.4.0},
      month =            {Sep},
      year =             {2022},
      note =             {GAP package},
      howpublished =     {\href           {https://gap-packages.github.io/recog}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{recog}}},
      keywords =         {group    recognition;    matrix   group   recognition;
                          permutation  group; black box group; composition tree;
                          Aschbacher classes; method selection},
      printedkey =       {NSH22}
    }

