#!/bin/sh

rm -f *.aux
rm -f *.lab
rm -f *.log
rm -f *.dvi
rm -f *.ps
rm -f *.pdf
rm -f *.bbl
rm -f *.ilg
rm -f *.ind
rm -f *.idx
rm -f *.out
rm -f *.html
rm -f *.tex
rm -f *.pnr
rm -f *.txt
rm -f *.blg
rm -f *.toc
rm -f *.six
rm -f *.brf
