#
gap> START_TEST("verification.tst");
gap> oldInfoLevel := InfoLevel(InfoRecog);;
gap> oldInfoOrbLevel := InfoLevel(InfoOrb);;
gap> SetInfoLevel(InfoRecog, 0);;
gap> SetInfoLevel(InfoOrb, 0);;

# Prints error if verification for G does not return true at least
# 4 ot of 5 times.
gap> testGroup := function(G)
>  local numSuccessful, i, ri, numTests;
>  numSuccessful := 0;
>  numTests := 5;
>  for i in [1..numTests] do
>    ri := RecogniseGroup(G);
>    if VerifyGroup(ri) = true then
>      numSuccessful := numSuccessful + 1;
>    fi;
>  od;
>  if numSuccessful < 4 then
>    Display(
>       "Verification for ", G, " was succesful only ", numSuccessful,
>       " out of ", numTests, " times"
>    );
>  fi;
> end;;

## Test some groups for which verification is expected to work
gap> matGroupList := [
>    SL(2,2), SL(2,3), SL(2,4), SL(2, 9), SL(2,13), SL(2, 53),
>    SL(3,2), SL(3,5), SL(3, 17),
>    SL(5,2),
>    Sp(2,2), Sp(2,4), Sp(2,3), Sp(4,2), Sp(4,3), Sp(6,2), Sp(6,3),
>    SO(3,2), SO(3,3), SO(1, 4,2), SO(1, 4,5),
>    Omega(1,4,3)
> ];;
gap> for G in matGroupList do
>  testGroup(G);
> od;
gap> permGroupList := [
>    SymmetricGroup(3), SymmetricGroup(5), SymmetricGroup(10),
>    AlternatingGroup(3), AlternatingGroup(8), AlternatingGroup(11),
>    Group((1,2), (3,4)), Group((1,2,3,4))
> ];;
gap> for G in permGroupList do
>  testGroup(G);
> od;

## Now test some groups for which verification returns false.

# Input: homomorphism G -> H
# Output: A recognition node for G with (leaf) children K and H where
# K is properly contained in the kernel of homom.
# If the optional argument kernGens (a list of elements of G) is given,
# then K is the group generated by kernGens.
# Sets some attributes of the recognition node, but possibly not everything
# that is needed for a proper recognition node.
gap> createIncorrectRecogNode := function(homom, kernGens...)
>   local G, gensG, gensH, H, kern, K, i, g, ri, riF, riK;
>   G := Source(homom);
>   gensG := GeneratorsOfGroup(G);
>   gensH := List(gensG, g -> ImageElm(homom, g));
>   H := GroupWithGenerators(gensH);
>   kern := Kernel(homom);

# Construct a proper subgroup K of kern (either cyclic or, if this is impossible, trivial)
# If kernGens is given, use this as generators of K instead
>   if Length(kernGens) = 0 then
>     K := Group(One(G));
>     for i in [1..10] do
>       g := Random(kern);
>       if Order(g) < Size(kern) and g <> One(G) then
>         K := Group(g);
>         break;
>       fi;
>     od;
>   else
>     kernGens := kernGens[1];
>     K := Group(kernGens);
>   fi;
>   ri := RecogNode(G);
>   riF := RecogniseGroup(H);
>   riK := RecogniseGroup(K);

# Set preimages of NiceGens(riF) in G. These lines are copied from RecogniseGeneric.
>   ri!.gensHmem := GeneratorsWithMemory(GeneratorsOfGroup(G));
>   ri!.pregensfacwithmem := CalcNiceGens(riF, ri!.gensHmem);
>   Setpregensfac(ri, StripMemory(ri!.pregensfacwithmem));

# Set remaining attributes of ri.
>   SetNiceGens(ri, Concatenation(pregensfac(ri), NiceGens(riK)));
>   SetCalcStdPresentation(ri, CalcStdPresentationGenericNonLeaf);
>   SetImageRecogNode(ri, riF);
>   SetKernelRecogNode(ri, riK);
>   SetParentRecogNode(riK, ri);
>   SetParentRecogNode(riF, ri);
>   SetHomom(ri, homom);
>   SetFilterObj(ri, IsReady);
>   return ri;
> end;;
gap> homByIm := function(gens, ims)
>   return GroupHomomorphismByImages(
>       Group(gens), Group(ims), gens, ims
>   );
> end;;
gap> homList := [
>   homByIm([(1,2), (3,4)], [(1,2), ()]), # Z_2^2 -> Z_2
>   homByIm([(1,2), (3,4), (5,6)], [(1,2), (), ()]), # Z_2^3 -> Z_2
>   homByIm([(1,2), (2,3)], [(1,2), (1,2)]), # sign homomorphism
>   homByIm([(1,2), (2,3)], [(), ()]) # trivial homomorphism
> ];;

# Test several times for each homomorphism to get different random elements in K
gap> for hom in homList do
>      for i in [1..20] do
>        if VerifyGroup(createIncorrectRecogNode(hom)) <> false then
>          Display("Incorrect recog node was verified");
>        fi;
>      od;
> od;
gap> SetInfoLevel(InfoRecog, oldInfoLevel);
gap> SetInfoLevel(InfoOrb, oldInfoOrbLevel);
gap> STOP_TEST("verification.tst");
