# Hints for HS:
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [2], dimensions := [20], 
       usemax := [ 1, 4, 6 ], 
       size := 44352000, atlasrepnrs := [9], 
       values := [ [ 10, 100 ], [ 11, 1100 ], [ 39, 3850 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [2], dimensions := [56], 
       usemax := [ 1, 6, 8 ], 
       size := 44352000, atlasrepnrs := [10], 
       values := [ [ 10, 100 ], [ 39, 3850 ], [ 56, 5600 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [2], dimensions := [132], 
       usemax := [ 5, 1, 2 ], 
       size := 44352000, atlasrepnrs := [11], 
       values := [ [ 11, 1100 ], [ 34, 100 ], [ 56, 176 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [2], dimensions := [518], 
       usemax := [ 1, 5, 7 ], 
       size := 44352000, atlasrepnrs := [12], 
       values := [ [ 34, 100 ], [ 88, 1100 ], [ 126, 4125 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [2], dimensions := [1000], 
       usemax := [ 1, 5, 7 ], 
       size := 44352000, atlasrepnrs := [13], 
       values := [ [ 34, 100 ], [ 66, 1100 ], [ 126, 4125 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [3], dimensions := [22], 
       usemax := [ 1, 2, 3 ], 
       size := 44352000, atlasrepnrs := [14], 
       values := [ [ 1, 100 ], [ 2, 176 ], [ 2, 176 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [3], dimensions := [49], 
       usemax := [ 3, 2, 5 ], 
       size := 44352000, atlasrepnrs := [15], 
       values := [ [ 2, 176 ], [ 56, 176 ], [ 77, 1100 ] ]
  ));
>>>SAME FIELD AND DIM
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [3], dimensions := [49], 
       usemax := [ 2, 3, 5 ], 
       size := 44352000, atlasrepnrs := [16], 
       values := [ [ 2, 176 ], [ 2, 176 ], [ 77, 1100 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [3], dimensions := [77], 
       usemax := [ 1, 4, 5 ], 
       size := 44352000, atlasrepnrs := [17], 
       values := [ [ 1, 100 ], [ 11, 1100 ], [ 11, 1100 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [3], dimensions := [154], 
       usemax := [ 5, 6, 7 ], 
       size := 44352000, atlasrepnrs := [18], 
       values := [ [ 11, 1100 ], [ 39, 3850 ], [ 42, 4125 ] ]
  ));
>>>SAME FIELD AND DIM
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [3], dimensions := [154], 
       usemax := [ 2, 3, 5 ], 
       size := 44352000, atlasrepnrs := [19], 
       values := [ [ 2, 176 ], [ 2, 176 ], [ 11, 1100 ] ]
  ));
>>>SAME FIELD AND DIM
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [3], dimensions := [154], 
       usemax := [ 2, 3, 5 ], 
       size := 44352000, atlasrepnrs := [20], 
       values := [ [ 2, 176 ], [ 2, 176 ], [ 11, 1100 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [3], dimensions := [231], 
       usemax := [ 4, 1, 6 ], 
       size := 44352000, atlasrepnrs := [21], 
       values := [ [ 11, 1100 ], [ 21, 100 ], [ 39, 3850 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [3], dimensions := [321], 
       usemax := [ 2, 3, 1 ], 
       size := 44352000, atlasrepnrs := [22], 
       values := [ [ 40, 176 ], [ 40, 176 ], [ 90, 100 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [3], dimensions := [693], 
       usemax := [ 5, 6, 2 ], 
       size := 44352000, atlasrepnrs := [23], 
       values := [ [ 11, 1100 ], [ 39, 3850 ], [ 42, 176 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [3], dimensions := [748], 
       usemax := [ 6, 1, 2 ], 
       size := 44352000, atlasrepnrs := [24], 
       values := [ [ 39, 3850 ], [ 55, 100 ], [ 56, 176 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [3], dimensions := [770], 
       usemax := [ 2, 3, 6 ], 
       size := 44352000, atlasrepnrs := [25], 
       values := [ [ 40, 176 ], [ 40, 176 ], [ 156, 3850 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [3], dimensions := [825], 
       usemax := [ 4, 1, 6 ], 
       size := 44352000, atlasrepnrs := [26], 
       values := [ [ 11, 1100 ], [ 21, 100 ], [ 39, 3850 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [4], dimensions := [896], 
       usemax := [ 1, 7, 5 ], 
       size := 44352000, atlasrepnrs := [27], 
       values := [ [ 70, 100 ], [ 126, 4125 ], [ 154, 1100 ] ]
  ));
>>>SAME FIELD AND DIM
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [4], dimensions := [896], 
       usemax := [ 1, 7, 5 ], 
       size := 44352000, atlasrepnrs := [28], 
       values := [ [ 70, 100 ], [ 126, 4125 ], [ 154, 1100 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [5], dimensions := [21], 
       usemax := [ 2, 3, 4 ], 
       size := 44352000, atlasrepnrs := [29], 
       values := [ [ 2, 176 ], [ 2, 176 ], [ 11, 1100 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [5], dimensions := [55], 
       usemax := [ 5, 2, 3 ], 
       size := 44352000, atlasrepnrs := [30], 
       values := [ [ 11, 1100 ], [ 38, 176 ], [ 38, 176 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [5], dimensions := [98], 
       usemax := [ 2, 3, 5 ], 
       size := 44352000, atlasrepnrs := [31], 
       values := [ [ 16, 176 ], [ 16, 176 ], [ 143, 1100 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [5], dimensions := [133], 
       usemax := [ 2, 3, 8 ], 
       size := 44352000, atlasrepnrs := [32], 
       values := [ [ 16, 176 ], [ 38, 176 ], [ 56, 5600 ] ]
  ));
>>>SAME FIELD AND DIM
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [5], dimensions := [133], 
       usemax := [ 2, 3, 8 ], 
       size := 44352000, atlasrepnrs := [33], 
       values := [ [ 38, 176 ], [ 38, 176 ], [ 56, 5600 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [5], dimensions := [175], 
       usemax := [ 2, 3, 4 ], 
       size := 44352000, atlasrepnrs := [34], 
       values := [ [ 2, 176 ], [ 2, 176 ], [ 11, 1100 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [5], dimensions := [210], 
       usemax := [ 2, 3, 10 ], 
       size := 44352000, atlasrepnrs := [35], 
       values := [ [ 38, 176 ], [ 38, 176 ], [ 58, 5775 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [5], dimensions := [280], 
       usemax := [ 3, 2, 5 ], 
       size := 44352000, atlasrepnrs := [36], 
       values := [ [ 16, 176 ], [ 126, 176 ], [ 231, 1100 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [5], dimensions := [518], 
       usemax := [ 2, 3, 10 ], 
       size := 44352000, atlasrepnrs := [37], 
       values := [ [ 38, 176 ], [ 38, 176 ], [ 58, 5775 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [5], dimensions := [650], 
       usemax := [ 2, 3, 6 ], 
       size := 44352000, atlasrepnrs := [38], 
       values := [ [ 38, 176 ], [ 38, 176 ], [ 39, 3850 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [7], dimensions := [22], 
       usemax := [ 1, 2, 3 ], 
       size := 44352000, atlasrepnrs := [39], 
       values := [ [ 1, 100 ], [ 2, 176 ], [ 2, 176 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [7], dimensions := [77], 
       usemax := [ 1, 4, 5 ], 
       size := 44352000, atlasrepnrs := [40], 
       values := [ [ 1, 100 ], [ 11, 1100 ], [ 11, 1100 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [7], dimensions := [154], 
       usemax := [ 5, 6, 7 ], 
       size := 44352000, atlasrepnrs := [41], 
       values := [ [ 11, 1100 ], [ 39, 3850 ], [ 42, 4125 ] ]
  ));
>>>SAME FIELD AND DIM
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [7], dimensions := [154], 
       usemax := [ 5, 2, 3 ], 
       size := 44352000, atlasrepnrs := [42], 
       values := [ [ 11, 1100 ], [ 42, 176 ], [ 42, 176 ] ]
  ));
>>>SAME FIELD AND DIM
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [7], dimensions := [154], 
       usemax := [ 2, 5, 3 ], 
       size := 44352000, atlasrepnrs := [43], 
       values := [ [ 2, 176 ], [ 11, 1100 ], [ 42, 176 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [7], dimensions := [175], 
       usemax := [ 2, 3, 4 ], 
       size := 44352000, atlasrepnrs := [44], 
       values := [ [ 2, 176 ], [ 2, 176 ], [ 11, 1100 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [7], dimensions := [231], 
       usemax := [ 4, 1, 6 ], 
       size := 44352000, atlasrepnrs := [45], 
       values := [ [ 11, 1100 ], [ 21, 100 ], [ 39, 3850 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [7], dimensions := [605], 
       usemax := [ 2, 3, 1 ], 
       size := 44352000, atlasrepnrs := [46], 
       values := [ [ 40, 176 ], [ 40, 176 ], [ 45, 100 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [7], dimensions := [693], 
       usemax := [ 5, 6, 2 ], 
       size := 44352000, atlasrepnrs := [47], 
       values := [ [ 11, 1100 ], [ 39, 3850 ], [ 42, 176 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [7], dimensions := [770], 
       usemax := [ 4, 5, 1 ], 
       size := 44352000, atlasrepnrs := [48], 
       values := [ [ 11, 1100 ], [ 11, 1100 ], [ 21, 100 ] ]
  ));
>>>SAME FIELD AND DIM
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [7], dimensions := [770], 
       usemax := [ 2, 3, 6 ], 
       size := 44352000, atlasrepnrs := [49], 
       values := [ [ 40, 176 ], [ 40, 176 ], [ 195, 3850 ] ]
  ));
>>>SAME FIELD AND DIM
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [7], dimensions := [770], 
       usemax := [ 2, 3, 6 ], 
       size := 44352000, atlasrepnrs := [50], 
       values := [ [ 40, 176 ], [ 40, 176 ], [ 195, 3850 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [7], dimensions := [803], 
       usemax := [ 7, 1, 10 ], 
       size := 44352000, atlasrepnrs := [51], 
       values := [ [ 42, 4125 ], [ 54, 100 ], [ 58, 5775 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [11], dimensions := [22], 
       usemax := [ 1, 2, 3 ], 
       size := 44352000, atlasrepnrs := [52], 
       values := [ [ 1, 100 ], [ 2, 176 ], [ 2, 176 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [11], dimensions := [77], 
       usemax := [ 1, 4, 5 ], 
       size := 44352000, atlasrepnrs := [53], 
       values := [ [ 1, 100 ], [ 11, 1100 ], [ 11, 1100 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [11], dimensions := [154], 
       usemax := [ 5, 6, 7 ], 
       size := 44352000, atlasrepnrs := [54], 
       values := [ [ 11, 1100 ], [ 39, 3850 ], [ 42, 4125 ] ]
  ));
>>>SAME FIELD AND DIM
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [11], dimensions := [154], 
       usemax := [ 5, 2, 3 ], 
       size := 44352000, atlasrepnrs := [55], 
       values := [ [ 11, 1100 ], [ 42, 176 ], [ 42, 176 ] ]
  ));
>>>SAME FIELD AND DIM
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [11], dimensions := [154], 
       usemax := [ 3, 5, 2 ], 
       size := 44352000, atlasrepnrs := [56], 
       values := [ [ 2, 176 ], [ 11, 1100 ], [ 42, 176 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [11], dimensions := [174], 
       usemax := [ 1, 2, 3 ], 
       size := 44352000, atlasrepnrs := [57], 
       values := [ [ 20, 100 ], [ 42, 176 ], [ 42, 176 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [11], dimensions := [231], 
       usemax := [ 4, 1, 6 ], 
       size := 44352000, atlasrepnrs := [58], 
       values := [ [ 11, 1100 ], [ 20, 100 ], [ 39, 3850 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [11], dimensions := [693], 
       usemax := [ 5, 6, 2 ], 
       size := 44352000, atlasrepnrs := [59], 
       values := [ [ 11, 1100 ], [ 39, 3850 ], [ 42, 176 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [11], dimensions := [770], 
       usemax := [ 4, 5, 1 ], 
       size := 44352000, atlasrepnrs := [60], 
       values := [ [ 11, 1100 ], [ 11, 1100 ], [ 20, 100 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [11], dimensions := [825], 
       usemax := [ 4, 1, 6 ], 
       size := 44352000, atlasrepnrs := [61], 
       values := [ [ 11, 1100 ], [ 20, 100 ], [ 39, 3850 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [11], dimensions := [854], 
       usemax := [ 1, 7, 5 ], 
       size := 44352000, atlasrepnrs := [62], 
       values := [ [ 45, 100 ], [ 126, 4125 ], [ 154, 1100 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [11], dimensions := [896], 
       usemax := [ 1, 6, 2 ], 
       size := 44352000, atlasrepnrs := [63], 
       values := [ [ 45, 100 ], [ 195, 3850 ], [ 210, 176 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [49], dimensions := [896], 
       usemax := [ 6, 5, 2 ], 
       size := 44352000, atlasrepnrs := [64], 
       values := [ [ 195, 3850 ], [ 209, 1100 ], [ 210, 176 ] ]
  ));
>>>SAME FIELD AND DIM
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [49], dimensions := [896], 
       usemax := [ 6, 5, 2 ], 
       size := 44352000, atlasrepnrs := [65], 
       values := [ [ 195, 3850 ], [ 209, 1100 ], [ 210, 176 ] ]
  ));
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [121], dimensions := [770], 
       usemax := [ 2, 3, 1 ], 
       size := 44352000, atlasrepnrs := [66], 
       values := [ [ 40, 176 ], [ 40, 176 ], [ 190, 100 ] ]
  ));
>>>SAME FIELD AND DIM
InstallAlmostSimpleHint( "HS", "StabChainHint",
  rec( name := "HS", fields := [121], dimensions := [770], 
       usemax := [ 2, 3, 1 ], 
       size := 44352000, atlasrepnrs := [67], 
       values := [ [ 40, 176 ], [ 40, 176 ], [ 190, 100 ] ]
  ));
